rust:
  - changed-files:
      - any-glob-to-any-file: crates/**

docs:
  - changed-files:
      - any-glob-to-any-file:
          - docs/**
          - "**/*.md"

ci:
  - changed-files:
      - any-glob-to-any-file: .github/**

docker:
  - changed-files:
      - any-glob-to-any-file:
          - Dockerfile
          - .dockerignore
